"""add import batches and category rules

Revision ID: 172b630db858
Revises: 64f3b4303222
Create Date: 2026-09-22 14:10:54.916955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172b630db858'
down_revision: Union[str, None] = '64f3b4303222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('dedupe_hash', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'transactions', 'import_batches', ['import_batch_id'], ['id'])
    op.create_index('ix_transactions_dedupe_hash', 'transactions', ['dedupe_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_dedupe_hash', table_name='transactions')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'dedupe_hash')
    op.drop_column('transactions', 'import_batch_id')
    op.drop_table('import_batches')
    op.drop_table('category_rules')
    # ### end Alembic commands ###
